version: '2'

services:
  postgres:
    image: 'postgres:9.5'
    volumes:
      - 'postgres:/var/lib/postgresql/data'

#  redis:
#    image: 'redis:3.2-alpine'
#    command: redis-server
#    ports:
#      - '6379:6379'
#    volumes:
#      - 'redis:/var/lib/redis/data'

  bundledata:
   image: onebitweb
   volumes:
    - '/var/lib/gems/2.3.0'
   command: "true"

  mailcatcher:
      image: yappabe/mailcatcher
      ports:
          - '1025:1025'
          - '1080:1080'

  website:
    depends_on:
      - 'postgres'
      - 'bundledata'
      - 'mailcatcher'
#      - 'redis'
    build: .
    ports:
      - '3000:3000'
    volumes:
      - '.:/home/app/onebnb_api'
    env_file:
      - '.env'

#  cable:
#    depends_on:
#      - 'redis'
#    build: .
#    command: puma -p 28080 cable/config.ru
#    ports:
#      - '28080:28080'
#    volumes:
#      - '.:/onebnb_api'
#    env_file:
#      - '.env'

volumes:
#  redis:
  postgres:
  bundledata:
